# Generated by Django 3.2.7 on 2021-11-26 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomC', models.CharField(max_length=200, verbose_name='NomCategorie')),
                ('unites', models.IntegerField(verbose_name='UnitesCategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomP', models.CharField(max_length=200, verbose_name='NomProduit')),
                ('unitesSP', models.IntegerField(verbose_name='UnitesProduitsEnStock')),
                ('seuil', models.IntegerField(verbose_name='SeuilAlerte')),
                ('nomC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.categorie')),
            ],
        ),
    ]
