# Generated by Django 3.2.7 on 2021-11-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_categorie_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='unites',
            field=models.CharField(max_length=200, verbose_name='UnitesCategorie'),
        ),
    ]
